### ISSUE TITLE
[WARC writer / protocol-okhttp] WARC-Truncated header issues and improvements

### ISSUE THREAD

**Issue by sebastian-nagel** [commoncrawl/nutch#10]
There are some oddities how truncated captures are recorded in WARC files. See also [Henry Thompson's report and the discussion in the Common Crawl user group](https://groups.google.com/d/topic/common-crawl/cVv4EPyRRPs/discussion).
- [x] (protocol-okhttp) reliably annotate content truncated by length limit:
   - this happens mostly (100 out of 110) for pages with `Content-Encoding: gzip`
   - no truncation flag is added if the [loop to read content chunk by chunk](https://github.com/commoncrawl/nutch/blob/b56a57764e839ab5af231d8a710a10003284b7d0/src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttpResponse.java#L158) is exited reaching the content limit exactly: verify and open issue to fix this in upstream Nutch ([NUTCH-2729](https://issues.apache.org/jira/browse/NUTCH-2729))
- [x] analyze truncations flagged as ["disconnect" due to an IOException](https://github.com/commoncrawl/nutch/blob/b56a57764e839ab5af231d8a710a10003284b7d0/src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttpResponse.java#L164)
   - in 3 analyzed WARC files all records flagged by "disconnect" have either "gzip" content encoding or "chunked" transfer encoding (or even both) - the reason could be also a broken encoding not a "network disconnect". Note: would need also to clarify how to [annotate](http://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/#warc-truncated) truncations due to protocol-level errors.
   - see #13 for more details
- [x] always add a Content-Length header to HTTP headers in WARC file, even if there wasn't one in the original HTTP response (eg. for chunked transfer encoding). Implemented in 3663f35.
- [x] (in the course) upgrade to latest okhttp library ([NUTCH-2728](https://issues.apache.org/jira/browse/NUTCH-2728))
- [x] port fixes to [StormCrawler](/DigitalPebble/storm-crawler): DigitalPebble/storm-crawler#757

**Comment by sebastian-nagel** [comment]
For analysis and verification see
- [cc-pyspark#9](/commoncrawl/cc-pyspark/pull/9) to mine (presumably) truncated records from WARC files
- [Python Notebook to aggregate metrics from the list of records](/sebastian-nagel/cc-notebooks-var/blob/master/warc-truncation-stats.ipynb)

**Comment by sebastian-nagel** [comment]
Implemented and fixed for August 2019 crawl (CC-MAIN-2019-35). Solution verified on [100 randomly selected WARC files](https://github.com/sebastian-nagel/cc-notebooks-var/blob/master/warc-truncation-stats-fixed.ipynb).

**Comment by tfmorris** [comment]
> Implemented and fixed for August 2019 crawl (CC-MAIN-2019-35). Solution verified on [100 randomly selected WARC files](https://github.com/sebastian-nagel/cc-notebooks-var/blob/master/warc-truncation-stats-fixed.ipynb).

The above notebook is now [here](https://github.com/commoncrawl/cc-notebooks/blob/main/warc-truncation/cc-main-2019-35-100-warc-files.ipynb)
