### ISSUE TITLE
WARC writer incorrectly adds extra line in response records between HTTP headers and payload content

### ISSUE THREAD

**Issue by sebastian-nagel** [commoncrawl/nutch#5]
(reported by @wumpus, thanks!)
The WARC writer adds a redundant line between the HTTP headers and the payload content of WARC response records. This contradicts the [HTTP standard](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Response_message) which requires exactly one single empty line between the response header fields and the payload content.

This bug affects all WARC files (resp. the response records) in the Common Crawl August 2018 crawl archives. This may cause the following problems when the WARC files are processed:
- a WARC reader/parser assumes only a single empty line, the extracted payload content starts with "\r\n". Leading new lines are usually ignored by HTML parsers, but will fail other parsers for PDF, office documents, etc.
- the payload length indicated in the HTTP `Content-Length` header (optional) is off by 2: the payload includes the leading "\r\n" while the header value does not include it.

**Comment by sebastian-nagel** [comment]
The HTTP headers are "recorded" by protocol plugins. A check of the plugins shows that they do not agree regarding
- the number of trailing line breaks (2 => one empty line)
- the type of the line break (`\r\n` or `n`)
- even the same plugin may record the headers differently for request and response headers

Response  | Request  | Plugin              | Nutch version
--------- | -------- | ------------------- | -------------
 2 `\r\n` | 2 `\r\n` | protocol-okhttp     | 1.15      | [implementation](https://github.com/commoncrawl/nutch/blob/cc/src/plugin/protocol-okhttp/src/java/org/apache/nutch/protocol/okhttp/OkHttp.java#L159)
 1 `\n`   | 2 `\r\n` | protocol-http       | 1.15      | [implementation](https://github.com/commoncrawl/nutch/blob/cc/src/plugin/protocol-http/src/java/org/apache/nutch/protocol/http/HttpResponse.java#L273)
 (not     | supported) | protocol-httpclient | 1.15
 1 `\r\n` | 2 `\r\n` | protocol-http       | 1.6 CC      | [implementation](https://github.com/commoncrawl/nutch/blob/cc-1.7/src/plugin/protocol-http/src/java/org/apache/nutch/protocol/http/HttpResponse.java)

This bug is caused by an upgrade to Nutch 1.15 and a change from protocol-http (Common Crawl's fork) to protocol-okhttp. The latter records both request and response headers with a trailing empty line. The WARC writer should not add an extra empty line then. Ideally, the protocol-http should be fixed to be consistent regarding line breaks.

**Comment by anjackson** [comment]
While [resolving a separate issue](https://github.com/iipc/webarchive-commons/issues/81) I noticed that the [`WARC-Payload-Digest`](https://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/#warc-payload-digest) and [`WARC-Block-Digest`](https://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/#warc-block-digest) values for `response` records in the `CC-MAIN-2018-34` collection appear to be broken. They should be identical for 'vanilla' `response` records, but the WARC I looked only the `WARC-Block-Digest` matched the actual payload bytes.

I then came across this issue, and am wondering whether this is down to the differences in whitespace handling? Or perhaps I should open this as a separate issue?

**Comment by sebastian-nagel** [comment]
Hi @anjackson, thanks for remembering me about the digests. The WARC files of the [September crawl](http://commoncrawl.org/2018/10/september-2018-crawl-archive-now-available/) are correct now. If time I'll want to unify the header format for all Nutch protocol plugins. Eventually, we'll fix the WARC files of the August crawl but that's cumbersome as the URL index will be wrong for a couple of days until all WARC files are rewritten and reindexed.

**Comment by sebastian-nagel** [comment]
Format unification of stored HTTP headers tracked in [NUTCH-2657](https://issues.apache.org/jira/browse/NUTCH-2657).

**Comment by sebastian-nagel** [comment]
- [NUTCH-2657](https://issues.apache.org/jira/browse/NUTCH-2657) is fixed
- issue document in [August 2018 crawl announcement](https://commoncrawl.org/2018/08/august-2018-crawl-archive-now-available/)
