### ISSUE TITLE
WarcRecordWriter performance improvements

### ISSUE THREAD

**Issue by sebastian-nagel** [commoncrawl/nutch#8]
According to [async-profiler](/jvm-profiling-tools/async-profiler), when writing WARC files the CPU time is mostly spent for:
- gzip compression
- SHA digests
- language detection
- charset detection

![warc_writer_prof](https://user-images.githubusercontent.com/1630582/60350546-136c1180-99c4-11e9-998d-bd89b5a8792b.png)
(interactive [SVG.zip](https://github.com/commoncrawl/nutch/files/3339651/fetcher.reduce.28673.async-prof.svg.zip))

Tasks to improve the performance:
- [x] improve performance charset detection, see #7 
- [x] avoid unnecessary recoding from UTF-8 to UTF-8, verify validity instead

**Comment by tfmorris** [comment]
* Since the vast majority of pages are in UTF-8 encoding, [decoding then reencoding ](https://github.com/commoncrawl/nutch/blob/cc/src/java/org/commoncrawl/util/LanguageDetector.java#L110)them seems very wasteful. 
* It might be useful to compare the performance of the [ICU charset detector](http://userguide.icu-project.org/conversion/detection) or [Google's](https://github.com/google/compact_enc_det) vs Tika's
* The entire payload doesn't need to be scanned  for character set detection. A few KB should be plenty (I think ICU defaults to 8 KB).

**Comment by sebastian-nagel** [comment]
>     * decoding then reencoding
Unfortunately, CLD2 may segfault when the input is not 100% valid UTF-8. That's worse because it will kill the task and we'll loose data and stop the crawling. I haven't yet looked for a method to only validate UTF-8, reencoding was just the simplest way in terms of coding. If you know one let me know.

>     * [ICU charset detector](http://userguide.icu-project.org/conversion/detection)

Tika uses a patched version of the ICU detector internally. The main improvement: it uses also the [declared encoding](http://icu-project.org/apiref/icu4j/com/ibm/icu/text/CharsetDetector.html#setDeclaredEncoding-java.lang.String-) as an additional hint while [ICU dectector](http://source.icu-project.org/repos/icu/trunk/icu4j/main/classes/core/src/com/ibm/icu/text/CharsetDetector.java) ignores it ([ICU-8737 - won't fix](https://unicode-org.atlassian.net/browse/ICU-8737))

> [Google's](https://github.com/google/compact_enc_det)
Thanks for the pointer, I wasn't aware of it. If time I test it. Would also require some work to prepare the Java native bindings and compile and deploy the lib in the cluster.

>     * The entire payload doesn't need to be scanned  for character set detection. A few KB should be plenty (I think ICU defaults to 8 KB).
Tika's detectors set limits internally ([HtmlEncodingDetector](https://github.com/apache/tika/blob/1.21/tika-parsers/src/main/java/org/apache/tika/parser/html/HtmlEncodingDetector.java#L82) and [txt.CharsetDetector](https://github.com/apache/tika/blob/1.21/tika-parsers/src/main/java/org/apache/tika/parser/txt/CharsetDetector.java#L58)).

**Comment by sebastian-nagel** [comment]
> vast majority of pages are in UTF-8 encoding, decoding then reencoding them seems very wasteful

Thanks, @tfmorris. Guava provides a [method to validate UTF-8](https://guava.dev/releases/25.0-jre/api/docs/com/google/common/base/Utf8.html#isWellFormed-byte:A-). Calling it beforehand (2e5b0b9) and re-encoding only invalid UTF-8 (invalid UTF-8 sequences are replaced when decoding to Java string) saves some time - roughly, validating UTF-8 takes only 20-25% of the time required for re-encoding.
In a [single WARC file](https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2018-43/segments/1539583508988.18/warc/CC-MAIN-20181015080248-20181015101748-00033.warc.gz) among 55,271 records there are 47,057 HTML pages encoded in UTF-8 and 617 of them fail to validate.

**Comment by sebastian-nagel** [comment]
Profile with the improvements in production: [fetcher.reduce.17657.async-prof.svg.zip](https://github.com/commoncrawl/nutch/files/3396357/fetcher.reduce.17657.async-prof.svg.zip)

I don't see any options for substantial improvements
- 18% language detection: 13% CLD2, 3%  Tika charset detection
- 37% gzip compression, mostly spent in libz.so
- 16% SHA-1 digests: since the [WARC spec](http://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/#warc-block-digest) explicitly does not recommend any hash algorithm, maybe the better solution is to switch to another algorithm in the future.

**Comment by chris-ha458** [comment]
> * 37% gzip compression, mostly spent in libz.so
> * 16% SHA-1 digests: since the [WARC spec](http://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/#warc-block-digest) explicitly does not recommend any hash algorithm, maybe the better solution is to switch to another algorithm in the future.

Replacing gzip could reduce time by atleast 50% and likely more due to leveraging multiprocessing.
migrating away from SHA-1 to SHA-2 would cost around 10% more though. 
Overall still faster 
* ( Compression 37% -> 18%, Digests 16% -> 18%.  Sum 53% -> 36%)

If it is migrated to BLAKE3, that would be cut down to around 25%.
Overall bit more faster
* ( Compression 37% -> 18%, Digests 16% -> 4%.  Sum 53% -> 22%)
